### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by frewsxcv** [frewsxcv/alert-after#2]

**Comment by Boddlnagg** [comment]
I just added a toast notification example using the Windows Runtime APIs to the `winrt` crate: https://github.com/contextfree/winrt-rust/blob/master/examples/toast_notify.rs.

The code is not as pretty as it should be, but it works (at least for me ... according to the official documentation the API requires an "App ID" where I pass `"myrustapp.exe"`, but it seems to work with an arbitrary string). Now someone has to write a nice Rust wrapper for Windows toast notifications and then this tool can use it 😉

**Comment by hoodie** [comment]
@Boddlnagg I'd love to see this added to [notify-rust](http://github.com/hoodie/notify-rust/) :D

**Comment by frewsxcv** [comment]
The code that @Boddlnagg shared seems somewhat straightforward so we could just do something similar for alert-after. I don't have a Windows machine to try it out on so I'm not going to do the implementation, but if someone else has a Windows machine and wants to submit a pull request, it'd be much appreciated.

**Comment by Boddlnagg** [comment]
@frewsxcv The code itself is fairly straightforward, but the `winrt` crate is quite a heavy dependency right now (in terms of code size and compile time). You should make sure that it's not downloaded on other OSes.

@hoodie The options offered by the Windows API seem quite incompatible with those offered by `notify-rust` right now ...

**Comment by frewsxcv** [comment]
>You should make sure that it's not downloaded on other OSes.

This is possible via http://doc.crates.io/specifying-dependencies.html#platform-specific-dependencies

https://github.com/frewsxcv/alert-after/blob/master/Cargo.toml#L16-L17

**Comment by hoodie** [comment]
@Boddlnagg still, it just added macOS support and it would be nice to have it all out of one hand, even if the feature overlap is not that high

**Comment by frewsxcv** [comment]
cc @guillaumegomez

**Comment by LeopoldArkham** [comment]
@frewsxcv Looking into this, I have a question: Shouldn't [line 38](https://github.com/frewsxcv/alert-after/blob/master/main.rs#L38) be
`match process::Command::new(program_name.clone()).args(&args[1..]).spawn() {`
instead of
`match process::Command::new(program_name.clone()).args(args).spawn() {`
?

Seems to me that the command's name is being passed to it as an argument. Did I miss something?

**Comment by GuillaumeGomez** [comment]
@LeopoldArkham: It's supposed to.

**Comment by LeopoldArkham** [comment]
Huh. Is that UNIX behavior? Because for me on windows, `aa echo Hello` produces "echo Hello" instead of the expected "Hello"

**Comment by GuillaumeGomez** [comment]
I didn't know this crate was working on Windows actually. But yes, only on unix.

**Comment by LeopoldArkham** [comment]
I'm adding windows support now; Thanks for clearing up!

**Comment by Boddlnagg** [comment]
Note that `winrt` requires at least Windows 8 (I have only tested in on Windows 10, but the WinRT was introduced in Windows 8, so it should work). I think this should be documented.

Furthermore, the example in the README `aa sleep 5` doesn't work on Windows: In good old `cmd.exe` there is no `sleep` command; in Powershell there *is* a `sleep` command, but it's a shell built-in (Cmdlet), so it won't work with `aa` (related to #8). There is an alternative `timeout` command that does something similar and works in `cmd` and Powershell, though. The `wget` example similarly won't usually work, because `wget` is usually not installed on Windows. Powershell has a default alias `wget` for the `Invoke-WebRequest` Cmdlet, but again, this won't work with `aa`, since there is no actual executable called `wget`.
